version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/app/templates/"
    schedule:
      interval: "monthly"
